"""Refactor bookings

Revision ID: f4c03ccdb9d9
Revises: f166861d4fe5
Create Date: 2026-03-14 10:38:07.771636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4c03ccdb9d9'
down_revision: Union[str, Sequence[str], None] = 'f166861d4fe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('start_time', sa.String(), nullable=True))
    op.add_column('bookings', sa.Column('end_time', sa.String(), nullable=True))
    op.add_column('bookings', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    op.add_column('bookings', sa.Column('expert_earning', sa.Numeric(precision=10, scale=2), nullable=True))
    
    op.execute("UPDATE bookings SET start_time = scheduled_time, end_time = scheduled_time, duration_minutes = 60, expert_earning = 50.00")
    
    op.alter_column('bookings', 'start_time', nullable=False)
    op.alter_column('bookings', 'end_time', nullable=False)
    op.alter_column('bookings', 'duration_minutes', nullable=False)
    op.alter_column('bookings', 'expert_earning', nullable=False)
    
    op.drop_column('bookings', 'scheduled_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('start_otp', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('scheduled_time', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('bookings', 'expert_earning')
    op.drop_column('bookings', 'duration_minutes')
    op.drop_column('bookings', 'end_time')
    op.drop_column('bookings', 'start_time')
    # ### end Alembic commands ###
